steps:
  - id: frontend:build
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "./client/Dockerfile",
        "-t",
        "${_IMAGE_PATH}$SHORT_SHA",
        ".",
      ]
  - id: frontend:push
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_IMAGE_PATH}$SHORT_SHA",
      ]
  - id: frontend:deploy
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_IMAGE_PATH}$SHORT_SHA",
        "--region",
        "${_REGION}",
        "--allow-unauthenticated",
        "--port",
        "3000",
      ]
images:
  - ${_IMAGE_PATH}$SHORT_SHA