steps:
  - id: api:build
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "./server/Dockerfile",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_CONTAINER_NAME}",
        ".",
      ]
  - id: api:push
    name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/${_CONTAINER_NAME}"]
  - id: db:build
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "./server/Dockerfile.migrate",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/db",
        ".",
      ]
  - id: db:push
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/db"]
  - id: db:migrate
    name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      - "-c"
      - "/buildstep/execute.sh -i ${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/db -e DATABASE_URL=$$DATABASE_URL -s study-hack:asia-northeast1:instance -- npx prisma migrate deploy"
    secretEnv: ["DATABASE_URL"]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
