steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "./server",
        "-t",
        "asia-northeast1-docker.pkg.dev/study-hack/web/frontend",
        ".",
      ]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast1-docker.pkg.dev/study-hack/web/frontend"]
