version: '3'
services:
  gcloud:
    container_name: gcloud
    image: google/cloud-sdk:alpine
    volumes:
      - ./terraform:/workspace
      - gcloud-config:/root/.config
    entrypoint: gcloud
    working_dir: /workspace
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.2.1
    env_file:
      - .env
    volumes:
      - ./terraform:/workspace
      - gcloud-config:/root/.config
    working_dir: /workspace
volumes:
  gcloud-config: