version: "3"
services:
  app:
    container_name: study_hack_app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/usr/local/app
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      DB_URL: db:5432
  db:
    container_name: study_hack_db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: study_hack
    volumes:
      - db_data:/var/lib/posrgresql/data
volumes:
  db_data:
