version: '3'
services:
  node:
    container_name: node
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/usr/local/app
    tty:  true
    ports:
      - 3000:3000
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: study_hack
    volumes:
      - db_data:/var/lib/posrgresql/data

volumes:
  db_data:
